services:
  - type: web
    name: cryptoa-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python crypto_analyzer.py
    envVars:
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
